### ISSUE TITLE
mcp-gsuite and oauth2client have different expectations regarding .gauth.json

### ISSUE THREAD

**Issue by nightscape** [MarkusPfundstein/mcp-gsuite#7]
oauth2client expects `.gauth.json` to only contain a single key-value pair:

<img width="665" alt="image" src="https://github.com/user-attachments/assets/969110d8-cf0a-489e-925f-8071eab9300c">

Whereas mcp-gsuite expects an additional `account` key:
https://github.com/MarkusPfundstein/mcp-gsuite/blob/main/src/mcp_gsuite/server.py#L78

It might be that uv resolved a different version of `oauth2client` for you where this constraint does not exist?
For me, `uv.lock` contains
```toml
[[package]]
name = "oauth2client"
version = "4.1.3"
```

**Comment by MarkusPfundstein** [comment]
Hm weird. I have 4.1.3 as well.

I just pushed a change that requires now the account information to be in a separated `.accounts.json` file.

**Comment by nightscape** [comment]
Ok, that part seems to work now 👍 
Closing this issues.
